<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <!-- This is an example of a URDF. -->
    <!-- As we move through the file, new things to note will be pointed out. -->
    <!-- It's not meant an example of GOOD design, but an example of some of the various features of URDF/xacro. -->



    <!-- This will include all the contents of example_include.xacro first. Go check it out! -->
    <xacro:include filename="example_include.xacro" />



    <!-- This first link called "world" is empty -->
    <link name="world"></link>

    <xacro:property name="link_1_length" value="0.2" />
    <xacro:property name="link_1_radius" value="0.1" />
    <xacro:property name="link_2_length" value="1" />
    <xacro:property name="link_2_radius" value="0.1" />
    <xacro:property name="link_3_length" value="0.2" />
    <xacro:property name="link_3_radius" value="0.1" />
    <xacro:property name="link_4_length" value="1" />
    <xacro:property name="link_4_radius" value="0.1" />
    <xacro:property name="link_5_length" value="0.3" />
    <xacro:property name="link_5_radius" value="0.1" />
    <xacro:property name="link_6_length" value="0.1" />
    <xacro:property name="link_6_radius" value="0.1" />

    <!-- joints -->

    <joint name="link_1_joint" type="revolute">
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="link_1_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <joint name="link_2_joint" type="revolute">
        <origin xyz="0 0 ${link_1_length}" rpy="0 0 0"/>
        <parent link="link_1_link"/>
        <child link="link_2_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>
    
    <joint name="link_3_joint" type="revolute">
        <origin xyz="0 0 ${link_2_length}" rpy="0 0 0"/>
        <parent link="link_2_link"/>
        <child link="link_3_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <joint name="link_4_joint" type="revolute">
        <origin xyz="0 0 ${link_3_length}" rpy="0 0 0"/>
        <parent link="link_3_link"/>
        <child link="link_4_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <joint name="link_5_joint" type="revolute">
        <origin xyz="0 0 ${link_4_length}" rpy="0 0 0"/>
        <parent link="link_4_link"/>
        <child link="link_5_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <joint name="link_6_joint" type="revolute">
        <origin xyz="0 0 ${link_5_length}" rpy="0 0 0"/>
        <parent link="link_5_link"/>
        <child link="link_6_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <!-- links -->

    <link name="link_1_link">
        <visual>
            <origin xyz="0 0 ${link_1_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_1_length}" radius="${link_1_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_1_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_1_length}" radius="${link_1_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_1_length}" radius="${link_1_radius}">
            <origin xyz="${link_1_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <link name="link_2_link">
        <visual>
            <origin xyz="0 0 ${link_2_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_2_length}" radius="${link_2_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_2_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${link_2_length}" radius="${link_2_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_2_length}" radius="${link_2_radius}">
            <origin xyz="${link_2_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <link name="link_3_link">
        <visual>
            <origin xyz="0 0 ${link_3_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_3_length}" radius="${link_3_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_3_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_3_length}" radius="${link_3_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_3_length}" radius="${link_3_radius}">
            <origin xyz="${link_3_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <link name="link_4_link">
        <visual>
            <origin xyz="0 0 ${link_4_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_4_length}" radius="${link_4_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_4_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_4_length}" radius="${link_4_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_4_length}" radius="${link_4_radius}">
            <origin xyz="${link_4_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <link name="link_5_link">
        <visual>
            <origin xyz="0 0 ${link_5_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_5_length}" radius="${link_5_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_5_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_5_length}" radius="${link_5_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_5_length}" radius="${link_5_radius}">
            <origin xyz="${link_5_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <link name="link_6_link">
        <visual>
            <origin xyz="0 0 ${link_6_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${link_6_length}" radius="${link_6_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${link_6_length/2} 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_6_length}" radius="${link_6_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${link_6_length}" radius="${link_6_radius}">
            <origin xyz="${link_6_length/2} 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <xacro:include filename="example_gazebo.xacro" />

</robot>
