# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - robot_link_0_joint
      - robot_link_1_joint
      - robot_link_2_joint
      - robot_link_3_joint
      - robot_link_4_joint
      - robot_link_5_joint