# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - robot_link_0_joint
      - robot_link_1_joint
      - robot_link_2_joint
      - robot_link_3_joint
      - robot_link_4_joint
      - robot_link_5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity